### PR TITLE
adds kubernetes node name to the request log

### PR DESCRIPTION
**Pull request by shamsimam**
## Changes proposed in this PR

- adds kubernetes node name to the request log

## Why are we making these changes?

Easier debuggability.

### CODE REVIEW

**Comment by sradack** [comment]
Please rebase.

**Comment by shamsimam** [comment]
Rebased. Please review this one after https://github.com/twosigma/waiter/pull/927

**Comment by sradack** [comment]
Please rebase

**Comment by shamsimam** [comment]
Rebased.

**Pull request merged**
