### PR TITLE
Avoid throwing exceptions in too many request in queue response

### PR DESCRIPTION
**Pull request by shamsimam**
## Changes proposed in this PR

- refactors exception->response to allow passing custom data maps
- refactors request preprocessors to use data->error-response instead of generating exceptions
- refactors process to run request preprocessors outside the async block

## Why are we making these changes?

The pre-processors do not need to execute inside the go-blocks nor need the overhead of generating exceptions while responding. By saving on these overheads, we can improve the overall performance while rejecting requests.

### CODE REVIEW

**Comment by dposada** [comment]
Do we have something that shows that this helped performance?

**Comment by shamsimam** [comment]
@dposada 

> Do we have something that shows that this helped performance?

Nope, I am currently manually testing with artificial load to verify that this helped. Did you want an automated test for this?

**Comment by dposada** [comment]
It might be nice to have some "proof" that this is better

**Comment by dposada** [comment]
Any thoughts on "proof" that this is better?

**Comment by shamsimam** [comment]
@dposada I have run the same stress test on Waiter for Max Queue length exceeded and Waiter is running fine.

The context for this PR has changed slightly as the template rendering has been identified as the main issue for slowness. This PR is now an incremental improvement where we can render the error response without throwing an exception.

**Pull request merged**
