### PR TITLE
uses https urls for redirects during OIDC auth

### PR DESCRIPTION
**Pull request by shamsimam**
## Changes proposed in this PR

- uses https urls for redirects during OIDC auth

## Why are we making these changes?

We wish to enforce use of https in OIDC authentication workflow.

### CODE REVIEW

**Comment by shamsimam** [comment]
> Have you considered redirecting via HTTPS to back to Waiter before issuing the redirect?

The HTTPS redirect would eventually end-up triggering the same redirect to the auth server (since x-waiter-auth cookie or headers would not change on the request). We are saving the extra round-trip by continuing the redirect to the OIDC auth server.

**Comment by sradack** [comment]
Agreed but then the redirect to IdP is secured and we avoid special casing
inside the OIDC code.

**Comment by shamsimam** [comment]
Updated the code to trigger SSL redirect to Waiter before triggering OIDC auth redirect

**Comment by shamsimam** [comment]
Hopefully, the request comes in with the `upgrade-insecure-requests` header and gets SSL redirected even before the OIDC auth workflow is triggered.

**Pull request merged**
